#! /bin/bash
echo "input:"
input=''
read input
echo "$input vers output:"
output=''
read output

echo "cp -r de $input vers $output"
if [ -d "$output" ];then
  echo -e "Oups, $output file EXIST!\n...you almost DESTROYED it."
  exit 0
else
  echo "file:$output does't exist then duplicate $input in:$output!"
  cp -r $input $output && cd $output && cat desktop.ini
  desktopold=''
  desktopnew=''
  echo "modif desktopold : "
  read desktopold
  echo "modif desktopnew : "
  read desktopnew
  echo "$desktopold $desktopnew"
  sed -i -r -e "s/$desktopold/$desktopnew/" desktop.ini && attrib desktop.ini +s +h
  for i in */ */*;do attrib +S "${i%/}";done
  # permet de restorer icon du dossier output
  cd ../ && attrib +S "${output%/}"
  echo "ready to work in $output"
fi
