#!/bin/zsh
for i in "$@"; do
	# get last part of path # echo ${$(pwd)##*/}
	lastPath=${$(pwd)##*/}
  if [[ $lastPath == 'code' ]] || [[ $lastPath == 'evt' ]] || [[ $lastPath == 'ray' ]]; then
		files=(~/optz/evnt/$i/*)
		# echo ${#files[@]} # echo array item
		if [[ $lastPath == 'code' ]] || [[ $lastPath == 'evt' ]]; then
			DIRECTORY="$(pwd)/evtSrc/$i/"
		fi
		if [[ $lastPath == 'ray' ]]; then
			DIRECTORY="$(pwd)/src/$i/"
		fi
		if [ -d "$DIRECTORY" ]; then
			echo "\n" $DIRECTORY "Exists!"
			for j in "${files[@]}"; do
				file=$j
				mv $file $DIRECTORY
				echo "copy ${${file}##*/} in evtSrc/${lastPath}/"
				# echo "copy ${file} in ${DIRECTORY}"
			done
		else
			echo "\n" $DIRECTORY "Does not exist! : "
			echo "Arghhh...! tu ne te trouves pas dans le dossier code ou evt ou ray \n
			ou aucun fichiers dans ${DIRECTORY}"
		fi
  fi
  # ls $(pwd)/evtSrc/$i/
done