#!/bin/zsh
# ls ~/optz/rCat/content/$i
for i in "$@"; do
	# get last part of path # echo ${$(pwd)##*/}
	lastPath=${$(pwd)##*/}
  if [[ $lastPath == 'HTML' ]]; then
		files=(~/optz/rCat/content/$i/*)
		# echo ${#files[@]} # echo array item
		DIRECTORY="$(pwd)/src/$i/images/"
		echo $DIRECTORY "Exists!"
		if [ -d "$DIRECTORY" ]; then
			for j in "${files[@]}"; do
				file=$j
				cp $file $DIRECTORY
				echo "cp $file in $DIRECTORY \n\n"
			done
		else
			echo "Arghhh...! tu ne te trouve pas dans le dossier HTML"
			echo $DIRECTORY "Does not exist!\n"
		fi
  fi
  # ls $(pwd)/src/$i/images
done