#!/bin/zsh
# ls ~/optz/rCat/content/$i
for i in "$@"; do
	# get last part of path # echo ${$(pwd)##*/}
	lastPath=${$(pwd)##*/}
  if [[ $lastPath == 'HTML' ]]; then
		files=(~/optz/rCat/content/$i/*)
		# echo ${#files[@]} # echo array item
		DIRECTORY="$(pwd)/src/$i/images/"
		if [ -d "$DIRECTORY" ]; then
			echo "\n\n" $DIRECTORY "Exists!"
			for j in "${files[@]}"; do
				file=$j
				cp $file $DIRECTORY
				echo "cp $file in $DIRECTORY"
			done
		else
			echo "\n\n" $DIRECTORY "Does not exist! : "
			echo "Arghhh...! tu ne te trouves pas dans le dossier HTML"
		fi
  fi
  # ls $(pwd)/src/$i/images
done