#!/bin/zsh
# ls ~/optz/rCat/content/$i
for i in "$@"; do
	# get last part of path
	# echo ${$(pwd)##*/}
	lastPath=${$(pwd)##*/}
  if [[ $lastPath == 'HTML' ]]; then
		imgitem=$(ls ~/optz/rCat/content/$i/insert_*)
		files=(~/optz/rCat/content/$i/*)
		# echo ${#files[@]} # echo array item
		for j in "${files[@]}"; do
			DIRECTORY="$(pwd)/src/$i/images/"
			if [ -d "$DIRECTORY" ]; then
				echo $DIRECTORY "Exists!"
				file=$j
				cp $file $DIRECTORY
				echo "\n\n"
				# echo $j
			else
				echo $DIRECTORY "Does not exist! \n\n"
			fi
		done
		# # echo $imgitem
		# DIRECTORY="$(pwd)/src/$i/images/"
		# if [ -d "$DIRECTORY" ]; then
		# 	echo $DIRECTORY "Exists!"
		# 	# echo "copie de $imgitem \n\n"
		# else
		# 	echo $DIRECTORY "Does not exist! \n\n"
		# fi
    # mv ~/optz/rCat/content/$i/insert_* $(pwd)/src/$i/images/
  else
    echo "Arghhh...! tu ne te trouve pas dans le dossier HTML"
  fi
  # ls $(pwd)/src/$i/images
done
    # echo "copie des fichiers : $(ls ~/optz/rCat/content/$i/insert_*)"
		# echo "vers $(pwd)/src/$i/images/"