#!/bin/zsh
echo "brand:"
brand=''
read brand
echo "date(mmyy):"
date_mmy=''
read date_mmy
cp=1
result=$(find /cygdrive/c/Users/mdevries/Pictures/$brand/cover/$date_mmy/ -type f ! -name '*.ini' 2> /dev/null)
if [ $result ];then
  while read -r line;do
    echo "cover n°$cp: ${line##/*/}"
    (( cp=$cp+1 ))
    open /cygdrive/c/Users/mdevries/Pictures/$brand/cover/$date_mmy/${line##/*/}
  done <<<"$result"
else
  echo "$brand's cover of $date_mmy isn't available"
fi