#!/bin/zsh
# ouverture planning-Manuel-2016
var=$(pwd)
if [[ $1 == '18' ]]; then
  echo "ouverture du planning 20${1}"
  cd K:/WEB/ && cygstart Plan_WEB_2018.xls
else
  echo "ouverture du planning 2017"
  cd K:/WEB/ && cygstart Plan_WEB_2017.xls
fi
cd $var
